export const projectLists = [
  {
    id: "1",
    link: "/project_detail/7",
    image: "/react-portfolio/img/port01.jpg",
    title: "최앤이치과 리뉴얼",
    category: "PC & MOBILE",
    text: "메인페이지 및 서브페이지 작업",
    time: "2017.4 ~ 2017.6",
  },
  {
    id: "2",
    link: "/project_detail/8",
    image: "/react-portfolio/img/port02.jpg",
    title: "필리핀 항공 리뉴얼",
    category: "PC & MOBILE",
    text: "메인 페이지 및 서브 페이지 작업",
    time: "2016.9 ~ 2017.3",
  },
  {
    id: "3",
    link: "/project_detail/9",
    image: "/react-portfolio/img/port03.jpg",
    title: "별 성형외과",
    category: "PC",
    time: "2016.9 ~ 2016.10",
    text: "PC 리뉴얼",
  },
  {
    id: "4",
    link: "/project_detail/3",
    image: "/react-portfolio/img/port06.jpg",
    title: "마이소호 홈페이지",
    category: "PC & MOBILE",
    text: "쇼핑몰 솔루션 마이소로 홈페이지 제작 및 유지 보수를 하였습니다",
    time: "",
  },
  {
    id: "5",
    link: "/project_detail/5",
    image: "/react-portfolio/img/port07.jpg",
    title: "마이소호 상점 디자인 템플릿",
    category: "MOBILE",
    text: "마이소호 쇼핑몰 솔루션의 기본 쇼핑몰 템플릿 예시 입니다.",
  },
  {
    id: "6",
    link: "/project_detail/4",
    image: "/react-portfolio/img/port04.jpg",
    title: "마이소호 관리자",
    category: "PC & MOBILE",
    text: "마이소호 솔루션의 관리자 사이트 입니다. 전체 페이지 제작 및 리뉴얼 유지 보수 등을 하였습니다.",
    time: "",
  },
  {
    id: "7",
    link: "/project_detail/6",
    image: "/react-portfolio/img/mylink.gif",
    title: "마이링크 신규 제작",
    category: "PC",
    text: "마이소호의 마이링크 서비스 신규 제작 퍼블리싱을 하였습니다.",
    time: "2021.03 ~ 2021.04",
  },
  {
    id: "8",
    link: "/project_detail/1",
    image: "/react-portfolio/img/makeshop_admin_main.png",
    title: "메이크샵 관리자 운영",
    category: "PC",
    text: "쇼핑몰 솔루션 서비스 메이크샵의 관리자 퍼블리싱 업무를 하였습니다.",
    time: "2021.05 ~ 2023.05",
  },
  {
    id: "9",
    link: "/project_detail/2",
    image: "/react-portfolio/img/makeshop_shop_default.gif",
    title: "메이크샵 상점 템플릿",
    category: "PC",
    text: "메이크샵 상점들의 쇼핑몰디자인 템플릿을 관리하여 이슈 사항이나 추가 기능들을 보완.",
    time: "2021.05 ~ 2023.05",
  },
  {
    id: "10",
    link: "/project_detail/13",
    image: "/react-portfolio/img/port08.jpg",
    title: "웅진씽크빅 홈페이지 관리",
    category: "PC",
    text: "리액트 리덕스를 사용하여 웅진씽크빅 홈페이지 페이지를 관리 할 수 있는 시스템을 개발했던 팀 프로젝트입니다. ",
    time: "2023.07 ~ 2023.08",
  },
  {
    id: "11",
    link: "/project_detail/10",
    image: "/react-portfolio/img/movieapp1.gif",
    title: "무비리스트",
    category: "PC",
    text: "영화 API를 활용하여 리액트로 만든 영화 리스트 입니다. ",
    time: "2023.06 ~ 2023.07",
  },
  {
    id: "12",
    link: "/project_detail/11",
    image: "/react-portfolio/img/todolist.gif",
    title: "todoList",
    category: "PC",
    text: "리액트로 만든 간단한 할일 목록 추가 및 삭제 가능한 투두리스트입니다.  ",
    time: "2023.05 ~ 2023.05",
  },
  {
    id: "13",
    link: "/project_detail/12",
    image: "/react-portfolio/img/blog.gif",
    title: "블로그",
    category: "PC",
    text: "리액트로 만든 간단한 할일 글 추가 및 삭제 가능한 블로그형식 투두리스트입니다. 모달창을 활용하여 수정이 가능하며 검색 및 리스트 정렬이 가능합니다.  ",
    time: "2023.05 ~ 2023.05",
  },
];
