export const detailInfo = [
  {
    id: 1,
    image1: "/react-portfolio/img/makeshop_admin_main.png",
    image2: "/react-portfolio/img/makeshop_admin_img.png",
    title: "메이크샵 관리자",
    desc1:
      "쇼핑몰 제작,판매, 운영, 홍보 등을 제공하는 쇼핑몰 솔루션 서비스 메이크샵의 관리자 퍼블리싱 업무를 하였습니다.",
    desc2:
      "고객의 요청 사항을 반영한 새로운 기능을 추가하거나 전체적인 페이지 리뉴얼과 디자인 변경 등 운영에 필요한 유지 보수 들을 진행 하였습니다.",
    source:
      "https://premium263.makeshop.co.kr/makeshop/newmanager/index.html?suburl=associated_service",
    techStack1: "Html",
    techStack2: "css",
    techStack3: "Javascript",
    type: "Solution",
    time: "2021 ~ 2023.4",
  },
  {
    id: 2,
    image1: "/react-portfolio/img/makeshop_shop_default.gif",
    image2: "/react-portfolio/img/makeshop_admin_design_edit.png",
    title: "메이크샵 상점 템플릿",
    desc1:
      "메이크샵 상점들의 쇼핑몰디자인 템플릿을 관리하여 이슈 사항이나 추가 기능들을 보완하는 퍼블리싱 업무를 담당하였습니다.",
    desc2:
      "상점의 페이지들을 관리자 편집 툴을 사용하여 html,css,javacsript로 관리하였습니다",
    source: "http://guest4.www264.freesell.co.kr/index.html",
    techStack1: "Html",
    techStack2: "css",
    techStack3: "Javascript",
    type: "Solution",
    time: "2021 ~ 2023.4",
  },
  {
    id: 3,
    image1: "/react-portfolio/img/port06.jpg",
    image2: "/react-portfolio/img/mysoho_front.gif",
    title: "마이소호 홈페이지",
    desc1: "마이소호 홈페이지 구축 및 리뉴얼 퍼블리싱을 담당하였숩니다.",
    desc2:
      "홈페이지를 운영하면서 생기는 고객들의 요청사항 불편사항 등을 개선하고 추가 페이지 혹은 페이지 보완에 필요한 퍼블리싱을 작업하였습니다.",
    source: "https://www.mysoho.com/index.html",
    techStack1: "Html",
    techStack2: "css",
    techStack3: "Javascript",
    type: "Solution",
    time: "2018 ~ 2021",
  },
  {
    id: 4,
    image1: "/react-portfolio/img/port04.jpg",
    image2: "/react-portfolio/img/mysoho_admin_m.gif",
    title: "마이소호 판매자센터 (관리자)",
    desc1:
      "쇼핑몰 솔루션 마이소호의 관리자 사이트입니다. 상점을 운영하면서 필요한 기능과 설정 사항들을 계속 운영하면서 필요한 퍼블리싱 업무들을 작업하였습니다.",
    desc2:
      "사이트를 유지하면서 발생하는 이슈들과 개선 사항들을 빠르게 반영하며 기능 개선 및 추가 시 필요한 퍼블리싱을 주로 담당했습니다.",
    source: "https://admin.mysoho.com/adm/main",
    techStack1: "Html",
    techStack2: "css",
    techStack3: "Javascript",
    type: "Solution",
    time: "2018 ~ 2021",
  },
  {
    id: 5,
    image1: "/react-portfolio/img/mysoho_shop.gif",
    image2: "/react-portfolio/img/mysoho_template_shop.gif",
    title: "마이소호 상점 퍼블리싱",
    desc1:
      "고객들이 이용하고 있는 마이소호 쇼핑몰들의 퍼블리싱을 담당하였으며 고객들이 이용가능한 쇼핑몰 기본 템플릿들을 퍼블리싱하였습니다.",
    desc2:
      "상점 쪽은 vue 프레임워크로 개발되어 vue로 개발 환경과 구조를 이해하고 vue로 개발된 코드에서 html, css , javascript 관련 코드 등을 수정하여 퍼블리싱 유지 보수를 진행했습니다.",
    source:
      "https://mysoho.com/template/mobile/index_design_preview.html?_gl=1*s178pl*_ga*NzQ1NjU2NzA3LjE2OTQxOTczNzE.*_ga_35XXRSZZQS*MTY5NDUwNDU4Ni42LjEuMTY5NDUwNzIwMS4zLjAuMA..",
    techStack1: "Html",
    techStack2: "css",
    techStack3: "Javascript",
    type: "Solution",
    time: "2018 ~ 2021",
  },
  {
    id: 6,
    image1: "/react-portfolio/img/mylink.gif",
    image2: "/react-portfolio/img/mylink_calendar.png",
    title: "마이링크 신규 제작",
    desc1:
      "링크 하나로 판매자가 등록한 판매 일정과 상품과 관련된 링크(주문서 등)를 보여줄 수 있는 마이링크 관련된 신규 페이지 제작 퍼블리싱을 담당했습니다.",
    desc2:
      "반응형으로 진행하였으며 fullcalendar 라이브러리를 활용하여 일정을 관리하는 캘린더 기능을 추가하였습니다.",
    source: "https://sohonara.mysoho.com/",
    techStack1: "Html",
    techStack2: "css",
    techStack3: "Javascript",
    type: "Solution",
    time: "2021.4 ~ 2021.5",
  },
  {
    id: 7,
    image1: "/react-portfolio/img/port01.jpg",
    image2: "/react-portfolio/img/choi.gif",
    title: "최앤이치과 리뉴얼",
    desc1: "최앤이치과 pc, mobile을 전체 리뉴얼 작업 하였습니다.",
    source: "http://www.choi-lee.com/",
    techStack1: "Html",
    techStack2: "css",
    techStack3: "Javascript",
    type: "WebAgency",
    time: "2017.4 ~ 2017.6",
  },
  {
    id: 8,
    image1: "/react-portfolio/img/port02.jpg",
    image2: "/react-portfolio/img/airline.gif",
    title: "필리핀 항공 리뉴얼",
    desc1: "필리핀 항공 pc, mobile을 전체 리뉴얼 작업 하였습니다.",
    desc2: "웹표준과 웹접근성을 고려하여 퍼블리싱을 진행했습니다.",
    source: "https://www.philippineair.co.kr/",
    techStack1: "Html",
    techStack2: "css",
    techStack3: "Javascript",
    type: "WebAgency",
    time: "2016.9 ~ 2017.3",
  },
  {
    id: 9,
    image1: "/react-portfolio/img/port03.jpg",
    image2: "/react-portfolio/img/byul.gif",
    title: "별 성형외과",
    desc1: "별 성형외과 항공 pc 전체 리뉴얼 작업, 유지 보수를 하였습니다.",
    source: "https://byulstar.com/",
    techStack1: "Html",
    techStack2: "css",
    techStack3: "Javascript",
    type: "WebAgency",
    time: "2016.9 ~ 2016.10",
  },
  {
    id: 10,
    image1: "/react-portfolio/img/movieapp1.gif",
    image2: "/react-portfolio/img/movieapp2.gif",
    title: "무비리스트",
    desc1: "영화 API를 활용하여 리액트로 만든 영화 리스트 입니다.",
    source: "https://github.com/definitely92/movieAppList",
    techStack1: "module.css",
    techStack2: "Javascript",
    techStack3: "react",
    type: "Toy",
    time: "2023.6 ~ 2023.07",
  },
  {
    id: 11,
    image1: "/react-portfolio/img/todoList.gif",
    image2: "",
    title: "투두리스트",
    desc1:
      "리액트로 만든 간단한 할일 목록 추가 및 삭제 가능한 투두리스트입니다.",
    source: "https://github.com/definitely92/todolist",
    techStack1: "css",
    techStack2: "Javascript",
    techStack3: "react",
    type: "Toy",
    time: "2023.5 ~ 2023.05",
  },
  {
    id: 12,
    image1: "/react-portfolio/img/blog.gif",
    image2: "",
    title: "블로그",
    desc1:
      "리액트로 만든 간단한 할일 글 추가 및 삭제 가능한 블로그형식 투두리스트입니다. 모달창을 활용하여 수정이 가능하며 검색 및 리스트 정렬이 가능합니다.",
    source: "https://github.com/definitely92/blog",
    techStack1: "css",
    techStack2: "Javascript",
    techStack3: "react",
    type: "Toy",
    time: "2023.6 ~ 2023.07",
  },
  {
    id: 13,
    image1: "/react-portfolio/img/port08.jpg",
    image2: "/react-portfolio/img/login.png",
    title: "웅진씽크빅",
    desc1:
      "리액트 리덕스를 사용하여 웅진씽크빅 홈페이지 페이지를 관리 할 수 있는 시스템을 개발했던 팀 프로젝트입니다. 로그인 기능과 로딩화면 페이지에 따른 로그인, 로그아웃 관리, 디자인 페이지 등을 작업하였습니다.",
    desc2:
      "로컬스토리지를 이용하여 로그인 기능을 구현하였고 로그인 성공 시 메뉴관리 페이지로 이동되게 개발하였습니다. 레이아웃과 디자인을 선택할 수 있는 편집 페이지 작업을 했습니다.",
    source:
      "https://github.com/udemy-project-camp-team2/homepage-system-team-2",
    techStack1: "styled-components",
    techStack2: "react",
    techStack3: "redux",
    type: "Toy",
    time: "2023.7 ~ 2023.08",
  },
];
